sortedcolors = [
    "colorless",
    "white",
    "blue",
    "azorious",
    "black",
    "orzhov",
    "dimir",
    "esper",
    "red",
    "boros",
    "izzet",
    "jeskai",
    "rakdos",
    "mardu",
    "grixis",
    "4c non-green",
    "green",
    "selesnya",
    "simic",
    "bant",
    "golgari",
    "abzan",
    "sultai",
    "4c non-red",
    "gruul",
    "naya",
    "temur",
    "4c non-black",
    "jund",
    "4c non-blue",
    "4c non-white",
    "5c",
]

def int2color(colorvector):
    return sortedcolors[colorvector]